branch-defaults:
  default:
    environment: Uda-env
environment-defaults:
  Uda-env:
    branch: null
    repository: null
global:
  application_name: uda
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli2
  sc: null
  workspace_type: Application
deploy:
  artifact: www/www.zip
