version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1
jobs:
  install__build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Install pip
          command: |
            sudo apt update
            sudo apt install -y python3-pip python-dev
      - run:
          name: Install AWS dependencies
          command: |
            sudo pip install awsebcli
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
  deploy:
    executor: aws-cli/default
    steps:
      - run:
          name: check
          command: echo "$PWD"
      - run:
          name: Backend Deploy
          command: cd udagram-api && eb deploy
      - run:
          name: Frontend Deploy
          command: cd udagram-frontend && aws s3 cp --recursive --acl public-read ./www s3://nano-cicd/
workflows:
  do:
    jobs:
      - install__build
      # - test
      - deploy