# eb init uda -r us-east-1
echo "$POSTGRES_USERNAME"
eb setenv APP_PORT=$APP_PORT DB_PORT=$DB_PORT POSTGRES_DB=$POSTGRES_DB POSTGRES_USERNAME=$POSTGRES_USERNAME POSTGRES_PASSWORD=$POSTGRES_PASSWORD URL=$URL JWT_SECRET=$JWT_SECRET POSTGRES_HOST=$POSTGRES_HOST